// examples/nuxt-remote/components/EchoInput.vue
<script setup lang="ts">
import { ref } from "vue";

const text = ref("");
</script>

<template>
  <div class="card" id="echo-card">
    <h2>Echo Input</h2>
    <input
      type="text"
      v-model="text"
      placeholder="Type here..."
    />
    <p class="echo">{{ text || "..." }}</p>
  </div>
</template>

// examples/react-router-remote/app/components/EchoInput.tsx
import { useState } from "react";

export function EchoInput() {
  const [text, setText] = useState("");

  return (
    <div className="card" id="echo-card">
      <h2>Echo Input</h2>
      <input
        type="text"
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Type here…"
      />
      <p className="echo">{text || "…"}</p>
    </div>
  );
}
