// examples/nuxt-remote/components/ToggleCheck.vue
<script setup lang="ts">
import { ref } from "vue";

const checked = ref(false);
</script>

<template>
  <div class="card" id="toggle-card">
    <h2>Toggle Checkbox</h2>
    <label class="checkbox-label">
      <input type="checkbox" v-model="checked" />
      Toggle me
    </label>
    <p>{{ checked ? "Checked" : "Unchecked" }}</p>
  </div>
</template>

// examples/tanstack-start-remote/src/components/ToggleCheck.tsx
import { useState } from "react";

export function ToggleCheck() {
  const [checked, setChecked] = useState(false);

  return (
    <div className="card" id="toggle-card">
      <h2>Toggle Checkbox</h2>
      <label className="checkbox-label">
        <input
          type="checkbox"
          checked={checked}
          onChange={(e) => setChecked(e.target.checked)}
        />
        Toggle me
      </label>
      <p>{checked ? "✅ Checked" : "⬜ Unchecked"}</p>
    </div>
  );
}
