// examples/nuxt-remote/components/Counter.vue
<script setup lang="ts">
import { useStore as useRemoteStore } from "@virtual-frame/nuxt/store";
import { useStore } from "@virtual-frame/vue";

const store = useRemoteStore();
const count = useStore<number>(store, ["count"]);
</script>

<template>
  <div class="card" id="counter-card">
    <h2>Counter</h2>
    <div class="counter">{{ count ?? 0 }}</div>
    <div style="display: flex; gap: 8px; justify-content: center">
      <button @click="store.count = (count ?? 0) - 1">- Decrement</button>
      <button @click="store.count = (count ?? 0) + 1">+ Increment</button>
    </div>
  </div>
</template>

// examples/nextjs-app-remote/app/components/Counter.tsx
"use client";

import { useStore } from "@virtual-frame/next";

export function Counter() {
  const store = useStore();
  const count = useStore<number>(["count"]);

  return (
    <div className="card" id="counter-card">
      <div className="counter">{count ?? 0}</div>
      <div className="actions">
        <button
          onClick={() => {
            store.count = (count ?? 0) - 1;
          }}
        >
          − Decrement
        </button>
        <button
          onClick={() => {
            store.count = (count ?? 0) + 1;
          }}
        >
          + Increment
        </button>
      </div>
    </div>
  );
}
