// examples/analog-remote/src/app/components/counter.component.ts
import { Component } from "@angular/core";
import {
  injectStore,
  injectStoreValue,
} from "@virtual-frame/analog/store";

@Component({
  selector: "app-counter",
  standalone: true,
  template: `
    <div class="card" id="counter-card">
      <h2>Counter</h2>
      <div class="counter">{{ count() ?? 0 }}</div>
      <div class="buttons">
        <button (click)="decrement()">- Decrement</button>
        <button (click)="increment()">+ Increment</button>
      </div>
    </div>
  `,
  styles: [
    `
    .card {
      background: rgba(255, 255, 255, 0.15);
      backdrop-filter: blur(10px);
      border: 1px solid rgba(255, 255, 255, 0.2);
      border-radius: 16px;
      padding: 24px;
      margin-bottom: 16px;
    }
    h2 { margin-bottom: 12px; }
    .counter {
      font-size: 48px;
      font-weight: bold;
      text-align: center;
      margin: 16px 0;
    }
    .buttons {
      display: flex;
      gap: 8px;
      justify-content: center;
    }
    button {
      background: rgba(255, 255, 255, 0.2);
      border: 1px solid rgba(255, 255, 255, 0.3);
      color: #fff;
      padding: 8px 20px;
      border-radius: 8px;
      font-size: 14px;
      cursor: pointer;
      transition: background 0.2s;
    }
    button:hover {
      background: rgba(255, 255, 255, 0.35);
    }
  `,
  ],
})
export class CounterComponent {
  store = injectStore();
  count = injectStoreValue<number>(this.store, ["count"]);

  increment() {
    this.store.count = (this.count() ?? 0) + 1;
  }

  decrement() {
    this.store.count = (this.count() ?? 0) - 1;
  }
}

// examples/react-remote/src/Counter.tsx
import { useStore } from "@virtual-frame/react";
import { useStore as useRemoteStore } from "@virtual-frame/react/store";

export function Counter() {
  const store = useRemoteStore();
  const count = useStore<number>(store, ["count"]);

  return (
    <div
      id="counter-card"
      style={{
        background: "#f0f4ff",
        borderRadius: 12,
        padding: 24,
        maxWidth: 320,
        textAlign: "center",
      }}
    >
      <h2 style={{ margin: "0 0 16px" }}>Remote Counter</h2>
      <div style={{ fontSize: 48, fontWeight: "bold", marginBottom: 16 }}>
        {count ?? 0}
      </div>
      <div style={{ display: "flex", gap: 8, justifyContent: "center" }}>
        <button
          onClick={() => {
            store.count = (count ?? 0) - 1;
          }}
          style={{
            padding: "8px 20px",
            fontSize: 16,
            borderRadius: 6,
            border: "1px solid #ccc",
            cursor: "pointer",
          }}
        >
          − Decrement
        </button>
        <button
          onClick={() => {
            store.count = (count ?? 0) + 1;
          }}
          style={{
            padding: "8px 20px",
            fontSize: 16,
            borderRadius: 6,
            border: "1px solid #ccc",
            cursor: "pointer",
          }}
        >
          + Increment
        </button>
      </div>
    </div>
  );
}
