// examples/sveltekit-remote/src/routes/about/+page.svelte
<div class="card">
  <h1>About</h1>
  <p>
    This is a second route in the remote SvelteKit app — use it to verify
    that client-side navigation inside the iframe continues to work after
    VirtualFrame has taken over.
  </p>
</div>

<nav>
  <a href="/">Home</a>
  <a href="/about">About</a>
</nav>

// examples/nextjs-app-remote/app/about/page.tsx
import { NextLink } from "../components/NextLink";

export default function AboutPage() {
  return (
    <>
      <div className="card" id="info-card">
        <h1>About</h1>
        <p>
          This is a second page in the remote Next.js app, demonstrating client-side navigation
          within a <code>&lt;virtual-frame&gt;</code>.
        </p>
        <p>
          Clicking <strong>Home</strong> below navigates back to the main page entirely inside the
          hidden iframe — the host page never reloads.
        </p>
      </div>

      <NextLink />
    </>
  );
}
